### ISSUE TITLE
Support Google Cloud Platform

### ISSUE THREAD

**Issue by rafaeljusto** [rafaeljusto/toglacier#89]
There's a similar service from AWS Glacier in Google Cloud Platform called [Nearline](https://cloud.google.com/storage-nearline/). it is good to have multiple options of cloud companies and let the user decide which one is better. The SDK for developing it is available in [GitHub](https://github.com/GoogleCloudPlatform/google-cloud-go).

In the future we could detect automatically the cheapest cloud company to send the backups.

**Comment by rafaeljusto** [comment]
Apparently Nearline isn't implemented in client yet.
https://github.com/GoogleCloudPlatform/google-cloud-go#supported-apis

**Comment by rafaeljusto** [comment]
Talking to Ben Mcllwain from Google, he said we could use the Google Storage client implementation that uses the same interface of the Nearline.

**Comment by CydeWeys** [comment]
To expand on this, Nearline isn't implemented as a separate product; it's simply a different storage class.  See here: https://cloud.google.com/storage/docs/storage-classes

If you grep the text of the GCS client you just linked for "NEARLINE" you'll see that storage class is an attribute on a bucket that can be set at creation time for that bucket.

Note that there's even a storage class called Coldline, which is cheaper than Nearline, that might be worth considering for your use case.

**Comment by rafaeljusto** [comment]
@CydeWeys  Thank you very much for the advice Ben! I will start to work on this and for sure will use [Coldline Storage](https://cloud.google.com/storage/docs/storage-classes#coldline).
